SELECT FirstName || " " || LastName || " " || Title as Employees FROM employees;
SELECT * FROM employees WHERE City = "Seattle";
SELECT * FROM employees WHERE City = "London";
SELECT * FROM employees WHERE Title LIKE '%Sales%';
SELECT * FROM employees WHERE Title LIKE '%Sales%' AND TItleOfCourtesy = "Mrs." or TItleOfCourtesy = "Ms." ;
SELECT FirstName || " " || LastName as name  FROM employees ORDER BY BirthDate ASC LIMIT 5;
SELECT FirstName || " " || LastName as name  FROM employees ORDER BY HireDate ASC LIMIT 5;
SELECT FirstName || " " || LastName as Name FROM employees WHERE ReportsTo is null;
SELECT e1.FirstName || " " || e1.LastName as employee_name, e2.FirstName || " " || e2.LastName as manager_name FROM employees AS e1 JOIN employees AS e2 ON e1.ReportsTo = e2.EmployeeID;SELECT e1.FirstName || " " || e1.LastName as employee_name, e2.FirstName || " " || e2.LastName as manager_name FROM employees AS e1 JOIN employees AS e2 ON e1.ReportsTo = e2.EmployeeID;
SELECT COUNT(EmployeeID) AS Females FROM employees WHERE TItleOfCourtesy = "Mrs." or TItleOfCourtesy = "Ms." ;
SELECT COUNT(EmployeeID) AS Males FROM employees WHERE TItleOfCourtesy = "Mr.";
SELECT City, COUNT(EmployeeID) AS NumberFromCity FROM employees GROUP BY City;
SELECT OrderID, FirstName || " " || LastName as Name FROM orders o JOIN employees e ON o.EmployeeID = e.EmployeeID;
SELECT OrderID,  CompanyName FROM orders  o JOIN shippers s ON o.ShipVia = s.ShipperID;
SELECT ShipCountry, COUNT(OrderID) AS NumberOfOrders FROM orders GROUP BY ShipCountry;
SELECT FirstName || " " || LastName as Name FROM orders o JOIN employees e ON o.EmployeeID = e.EmployeeID GROUP BY Name ORDER BY COUNT(e.EmployeeID) DESC LIMIT 1;
SELECT CompanyName AS Customer FROM orders o JOIN customers c ON o.CustomerID = c.CustomerID GROUP BY Customer ORDER BY COUNT(c.CustomerID) DESC LIMIT 1;
SELECT o.OrderID, e.FirstName || " " || e.LastName as Employee, c.CompanyName AS Customer FROM orders o JOIN employees e JOIN customers c ON o.CustomerID = c.CustomerID AND o.EmployeeID = e.EmployeeID;
SELECT c.CompanyName AS Customer,  s.CompanyName AS Shipper FROM orders o JOIN shippers s JOIN customers c ON o.CustomerID = c.CustomerID AND o.ShipVia = s.ShipperID;
